### ISSUE TITLE
LargerThan and LessThan compare does not support float64

### ISSUE THREAD

**Issue by puyangsky** [itsubaki/gostream-core#3]
https://github.com/itsubaki/gocep/blob/f070505cd522ff7e8216060715e58c8a969bf9da/parser.go#L173

**Comment by itsubaki** [comment]
I support float64 selector.

https://github.com/itsubaki/gostream-core/blob/9a3100052e80e1b0f60e30c53a0a263e822abe63/pkg/parser/parser_test.go#L20
